spring:
  application:
    name: ashen-hello-feign
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    encoding: UTF-8
    servlet:
      content-type: text/html

server:
  port: 9200

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/